Parameters:
  SubnetId:
    Type: String
    Default: subnet-0c43da3cb089bbc50
  SecurityGroupId:
    Type: String
    Default: sg-070d5c18c4e9c9f4e
  ImageId:
    Type: String
    Default: ami-02a53b0d62d37a757

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref ImageId
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
